frame = "full"
idle = true
maximized = false
# neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = true
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false

