# fork = false
frame = "full"
idle = true
maximized = false
# neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = true
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font]
normal =["CodeNewRoman Nerd Font Mono"] # Will use the bundled Fira Code Nerd Font by default
size = 20.0
style = "Bold"
# style = "W600"

# Add these lines for transparency 
transparency = true 
transparency_amount = 0.6
background_opacity = 0.6
