

# Custom color scheme

# Set syntax highlighting colors
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_STYLES[unknown-token]="fg=${DARK_RED}"  # Command not found
ZSH_HIGHLIGHT_STYLES[default]="fg=${DARK_BLUE}"       # Command found



# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/raghav/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/raghav/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/raghav/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/raghav/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Alias
alias ls='lsd -a'
alias install='sudo nala install'
alias purge='sudo nala purge'
alias update='sudo nala update && sudo nala full-upgrade -y'
alias lgin='bash ~/Documets/scripts/login.sh'
alias lgout='bash ~/Documents/scripts/logout.sh'

# StartUp
# fastfetch -c $HOME/.config/fastfetch/config-compact.jsonc


eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
