        . "/home/raghav/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/raghav/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Alias
alias ls='lsd -a'
alias install='sudo nala install'
alias purge='sudo nala purge'
alias update='sudo nala update && sudo nala full-upgrade -y'
alias lgin='bash ~/Documets/scripts/login.sh'
alias lgout='bash ~/Documents/scripts/logout.sh'

# StartUp
# fastfetch -c $HOME/.config/fastfetch/config-compact.jsonc


eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
